//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseFirstWpf.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filials
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public DateTime Opening_Date { get; set; }
        public string Note { get; set; }
        public int No { get; set; }
        public Filials Clone()
        { 
            Filials filial = new Filials()
            {
                 Address=this.Address,
                  Id=this.Id,
                   Name=this.Name,
                    Note=this.Note,
                     Opening_Date=this.Opening_Date
            };
            return filial;
        }
    }
}
